name: R Test Deploy to shiny

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy-shiny:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages
        run: |
          R -e 'install.packages("rsconnect")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("caret")'
          R -e 'install.packages("fastDummies")'
          R -e 'install.packages("base64enc")'
          R -e 'install.packages("bslib")'
          R -e 'install.packages("cachem")'
          R -e 'install.packages("commonmark")'
          R -e 'install.packages("crayon")'
          R -e 'install.packages("fastmap")'
          R -e 'install.packages("fontawesome")'
          R -e 'install.packages("fs")'
          R -e 'install.packages("htmltools")'
          R -e 'install.packages("httpuv")'

      - name: Deploy to shinyapps.io
        env:
          APPNAME: Test
          ACCOUNT: nickmwip
          SERVER: shinyapps.io
        run: |
           rsconnect::setAccountInfo('${{ secrets.RSCONNECT_USER }}', '${{ secrets.RSCONNECT_TOKEN }}', "${{ secrets.RSCONNECT_SECRET }}")
           rsconnect::deployApp(appName = "${{ env.APPNAME }}", account = "${{ env.ACCOUNT }}", server = "${{ env.SERVER }}")
        shell: Rscript {0}
